### ISSUE TITLE
C pété ton truc 

### ISSUE THREAD

**Issue by mrallan140** [Neeptossss/cfmd#1]
Ca marche pas avec https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack J'ai une erreur LWGJL le chef !!

**Comment by Neeptossss** [comment]
> Ca marche pas avec https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack J'ai une erreur LWGJL le chef !!

The tool is not related with the LWGL library please refer to the https://github.com/LWJGL/lwjgl3 issues for further informations

**Comment by mrallan140** [comment]
Sure i will look a it thank for the response .
